### ISSUE TITLE
UseIdentityServerBearerTokenAuthentication on Web Api 1?

### ISSUE THREAD

**Issue by abcplex** [IdentityServer/IdentityServer3.AccessTokenValidation#45]
How can I consume JWT from Web Api 1. In Web Api 2 I can use 

            app.UseIdentityServerBearerTokenAuthentication(new IdentityServerBearerTokenAuthenticationOptions
                {
                    Authority = "https://localhost:44333",
                    ValidationMode = ValidationMode.ValidationEndpoint,

                    RequiredScopes = new[] { "api1" }
                });

But how to do this in Web Api 1?

**Comment by leastprivilege** [comment]
You'd have to implement that yourself using some jwt library, e.g. The one from Microsoft.

**Comment by abcplex** [comment]
@leastprivilege Please help me to create that. It will be helpful for others as well. Just a small guide will be appreciated.

**Comment by abcplex** [comment]
@leastprivilege Is this link is fine http://markwalsh.io/development/2014/12/02/ASP.Net%20Web%20API%20with%20JWT/

**Comment by leastprivilege** [comment]
Thats probably a good starting point.

— 
cheers
Dominick Baier


On 13 Sep 2015 at 14:29:52, abcplex (notifications@github.com) wrote:

@leastprivilege Is this link is fine http://markwalsh.io/development/2014/12/02/ASP.Net%20Web%20API%20with%20JWT/

**Comment by abcplex** [comment]
@leastprivilege please help me to find ValidAudience, ValidIssuer and IssuerSigningToken. I think I have to hit IdSvr https://SERVER/.well-known/openid-configuration to get the ValidIssuer which will be issuer, IssuerSigningToken which will be x5c? What about ValidAudience? Please help

**Comment by abcplex** [comment]
OK at least tell me what parameters are I need to put in TokenValidationParameters and where are they find in .well-known/openid-configuration.  Since all applications are mine I can also put them in web.config. Please help.

**Comment by abcplex** [comment]
Dear @leastprivilege , can you please check why I am getting this error?

        private static TokenValidationParameters GetValidationParameters()
        {
            var bytes = Convert.FromBase64String("X5c");
            var token = new BinarySecretSecurityToken(bytes);
            return new TokenValidationParameters
            {
                ValidAudience = "http://MyServer/resources",
                ValidIssuer = "http://MyServer",
                IssuerSigningKeyResolver = (arbitrarily, declaring, these, parameters) => { return token.SecurityKeys.First(); },
                IssuerSigningToken = token
            };
        }

            var tokenHandler = new JwtSecurityTokenHandler();
            var validationParameters = GetValidationParameters();

            SecurityToken validToken;
            var jwt = "JWTToken";
            var principal = tokenHandler.ValidateToken(jwt, validationParameters, out validToken);

Error,

IDX10502: Signature validation failed. Key tried: 'System.IdentityModel.Tokens.InMemorySymmetricSecurityKey'.
Exception caught:
 'System.InvalidOperationException: IDX10632: SymmetricSecurityKey.GetKeyedHashAlgorithm( 'http://www.w3.org/2001/04/xmldsig-more#rsa-sha256' ) threw an exception.
SymmetricSecurityKey: 'System.IdentityModel.Tokens.InMemorySymmetricSecurityKey'
SignatureAlgorithm: 'http://www.w3.org/2001/04/xmldsig-more#rsa-sha256', check to make sure the SignatureAlgorithm is supported.
Exception: 'System.InvalidOperationException: Crypto algorithm 'http://www.w3.org/2001/04/xmldsig-more#rsa-sha256' not supported in this context.
   at System.IdentityModel.CryptoHelper.CreateKeyedHashAlgorithm(Byte[] key, String algorithm)
   at System.IdentityModel.Tokens.InMemorySymmetricSecurityKey.GetKeyedHashAlgorithm(String algorithm)
   at System.IdentityModel.Tokens.SymmetricSignatureProvider..ctor(SymmetricSecurityKey key, String algorithm) in c:\workspace\WilsonForDotNet45Release\src\System.IdentityModel.Tokens.Jwt\SymmetricSignatureProvider.cs:line 74'. ---> System.InvalidOperationException: Crypto algorithm 'http://www.w3.org/2001/04/xmldsig-more#rsa-sha256' not supported in this context.
   at System.IdentityModel.CryptoHelper.CreateKeyedHashAlgorithm(Byte[] key, String algorithm)
   at System.IdentityModel.Tokens.InMemorySymmetricSecurityKey.GetKeyedHashAlgorithm(String algorithm)
   at System.IdentityModel.Tokens.SymmetricSignatureProvider..ctor(SymmetricSecurityKey key, String algorithm) in c:\workspace\WilsonForDotNet45Release\src\System.IdentityModel.Tokens.Jwt\SymmetricSignatureProvider.cs:line 74
   --- End of inner exception stack trace ---
   at System.IdentityModel.Tokens.SymmetricSignatureProvider..ctor(SymmetricSecurityKey key, String algorithm) in c:\workspace\WilsonForDotNet45Release\src\System.IdentityModel.Tokens.Jwt\SymmetricSignatureProvider.cs:line 83
   at System.IdentityModel.Tokens.SignatureProviderFactory.CreateProvider(SecurityKey key, String algorithm, Boolean willCreateSignatures) in c:\workspace\WilsonForDotNet45Release\src\System.IdentityModel.Tokens.Jwt\SignatureProviderFactory.cs:line 246
   at System.IdentityModel.Tokens.SignatureProviderFactory.CreateForVerifying(SecurityKey key, String algorithm) in c:\workspace\WilsonForDotNet45Release\src\System.IdentityModel.Tokens.Jwt\SignatureProviderFactory.cs:line 187
   at System.IdentityModel.Tokens.JwtSecurityTokenHandler.ValidateSignature(Byte[] encodedBytes, Byte[] signature, SecurityKey key, String algorithm) in c:\workspace\WilsonForDotNet45Release\src\System.IdentityModel.Tokens.Jwt\JwtSecurityTokenHandler.cs:line 863
   at System.IdentityModel.Tokens.JwtSecurityTokenHandler.ValidateSignature(String token, TokenValidationParameters validationParameters) in c:\workspace\WilsonForDotNet45Release\src\System.IdentityModel.Tokens.Jwt\JwtSecurityTokenHandler.cs:line 949'.
token: '{"typ":"JWT","alg":"RS256","x5t":"a3rMUgMFv9tPclLa6yF3zAkfquE","kid":"a3rMUgMFv9tPclLa6yF3zAkfquE"}.{"client_id":"mobile","scope":"molapi","sub":"1","amr":"password","auth_time":1442151448,"idp":"idsrv","unique_id":"11","role":["Employer","Employee","SA"],"iss":"http://10.30.1.154/SSO/server","aud":"http://10.30.1.154/SSO/server/resources","exp":1442155048,"nbf":1442151448}'

Inner Exception,

{"IDX10632: SymmetricSecurityKey.GetKeyedHashAlgorithm( 'http://www.w3.org/2001/04/xmldsig-more#rsa-sha256' ) threw an exception.\nSymmetricSecurityKey: 'System.IdentityModel.Tokens.InMemorySymmetricSecurityKey'\nSignatureAlgorithm: 'http://www.w3.org/2001/04/xmldsig-more#rsa-sha256', check to make sure the SignatureAlgorithm is supported.\nException: 'System.InvalidOperationException: Crypto algorithm 'http://www.w3.org/2001/04/xmldsig-more#rsa-sha256' not supported in this context.\r\n   at System.IdentityModel.CryptoHelper.CreateKeyedHashAlgorithm(Byte[] key, String algorithm)\r\n   at System.IdentityModel.Tokens.InMemorySymmetricSecurityKey.GetKeyedHashAlgorithm(String algorithm)\r\n   at System.IdentityModel.Tokens.SymmetricSignatureProvider..ctor(SymmetricSecurityKey key, String algorithm) in c:\\workspace\\WilsonForDotNet45Release\\src\\System.IdentityModel.Tokens.Jwt\\SymmetricSignatureProvider.cs:line 74'."}

**Comment by abcplex** [comment]
@leastprivilege ok got it just replace BinarySecretSecurityToken with X509SecurityToken it works. So does this means that if I don't exception then it's a valid token? correct? Does this also means it will validate the expiry of token as well? Anything I am missing? Thanks

**Comment by leastprivilege** [comment]
the handler will throw an exception is something is wrong.
