### ISSUE TITLE
AccessTokenValidation broken after System.IdentityModel.Tokens.Jwt 5.0.0 (6/27/2016) update

### ISSUE THREAD

**Issue by ceastwood** [IdentityServer/IdentityServer3.AccessTokenValidation#94]
After an upgrade of  System.IdentityModel.Tokens.Jwt 5.0.0 (6/27/2016) due to another project dependency; a project using accesstokenvalidation fails to complete it's owin startup. I went looking and it seems this new 5.0.0 version has moved TokenValidationParameters to the Microsoft namespace (was previously under System)

**Stacktrace:**
System.TypeLoadException: Could not load type 'System.IdentityModel.Tokens.TokenValidationParameters' from assembly 'System.IdentityModel.Tokens.Jwt, Version=5.0.0.127, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
   at Owin.IdentityServerBearerTokenValidationAppBuilderExtensions.<>c__DisplayClass9.<ConfigureLocalValidation>b__8()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at Owin.IdentityServerBearerTokenValidationAppBuilderExtensions.UseIdentityServerBearerTokenAuthentication(IAppBuilder app, IdentityServerBearerTokenAuthenticationOptions options) in c:\local\identity\server3\AccessTokenValidation\source\AccessTokenValidation\IdentityServerBearerTokenValidationAppBuilderExtensions.cs:line 46
   at projectabc.Startup.Configuration(IAppBuilder app) in C:\dev\projectabc\Startup.cs:line 39

**Comment by leastprivilege** [comment]
There is not a lot we can do. We are only wrapping the MS JWT middleware.

They don't seem to be compatible with the new System.IdentityModel version. Open an issue in Katana.

**Comment by leastprivilege** [comment]
Let us know if Microsoft wants to update their MW - so we can use their new version. closing for now.

**Comment by brentschmaltz** [comment]
@ceastwood What is the project dependency that needs 5.0?
